services:
  backend_api:
    build: .
    expose:
      - 3000

  load_balancer:
    image: nginx:latest
    depends_on:
      - backend_api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80